custom error page
ines-mgg/Challenge-S1-4IW2 pull request #10
Opened 2024-01-06 14:27 UTC by ines-mgg

2024-01-06 17:50 UTC, grdnvictor requested changes
Fais une page dans le style des pages qu'on a déjà pour le site facturo (en plus simple)
Un truc qui prend toute la page avec logo facturo, le texte d'erreur et un bouton genre retour au site (ajoute une TODO dans le code pour que la redirection se fasse vers le dashboard si le mec est connecté ou au site s'il l'est pas (à voir))

2024-01-06 17:59 UTC, ines-mgg commented
> Fais une page dans le style des pages qu'on a déjà pour le site facturo (en plus simple) Un truc qui prend toute la page avec logo facturo, le texte d'erreur et un bouton genre retour au site (ajoute une TODO dans le code pour que la redirection se fasse vers le dashboard si le mec est connecté ou au site s'il l'est pas (à voir))

Je sais pas si la redirection au dashboard sera possible ([doc symfony](https://symfony.com/doc/current/controller/error_pages.html#security-404-pages)), une redirection sur la page d'accueil.
Je te ping dès que j'ai fait les modifs

2024-01-06 18:34 UTC, ines-mgg commented
@grdnvictor ok collègue, donne ton avis

2024-01-08 20:29 UTC, grdnvictor approved these changes
Bon pour le moment, à voir si on a d'autres infos à mettre sur ce type de page 👍

2024-01-08 20:54 UTC, merged